# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - crgar-quiz-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://crgarquizacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_384ae4e888d64ef6b28c9f85b8d76bb2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5526aa55e3884c5d94aed7db0c0099dc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: crgarquizacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_384ae4e888d64ef6b28c9f85b8d76bb2 }}/quiz:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'crgar-quiz-webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7d41ccc3c10c4169a0dc842bbc36e66d }}
        images: 'crgarquizacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_384ae4e888d64ef6b28c9f85b8d76bb2 }}/quiz:${{ github.sha }}'